### ISSUE TITLE
11번가 필터 노드 1개 이하 결과시 오류

### ISSUE THREAD

**Issue by tyl1996** [Meoseon-Division/node-red-contrib-ssafy-meoseon#4]
https://github.com/Meoseon-Division/node-red-contrib-ssafy-meoseon/blob/beba544d89d87cbebd5e48fe6967efc67dfcc8f0/Meoseon/shopping-filter.js#L46-L56

11번가 필터 노드에서 `msg.payload.ProductSearchResponse.Products.Product;`는 2개 이상의 결과는 array형태로 오지만, 1개의 결과만 있는 경우 object로 오고 있습니다.
`list.sort`는 array가 아닌 경우에 오류가 발생하고 있어 개선이 필요합니다

오류메세지는 다음과 같습니다 `"TypeError: Cannot read property 'sort' of undefined"`

**Comment by keelim** [comment]
👍👍
